export const EDUCATION = {
  heart: {
    title: 'Heart Health',
    emoji: '❤️',
    color: '#DC2626',
    colorBg: '#FEF2F2',
    overview: 'The heart pumps about 2,000 gallons of blood daily. Cardiovascular disease is the world\'s leading cause of death, yet up to 80% of cases are preventable through lifestyle changes.',
    sections: [
      {
        title: 'How to Strengthen Your Heart',
        icon: '💪',
        tips: [
          'Exercise 150 minutes per week — even brisk walking counts',
          'Eat heart-healthy foods: fish, nuts, olive oil, vegetables, fruits',
          'Reduce salt intake to less than 5g per day',
          'Maintain a healthy weight — even 5-10% weight loss helps',
          'Quit smoking — heart attack risk halves within a year of quitting',
          'Limit alcohol to 1-2 units per day maximum',
          'Manage stress through prayer, meditation, or deep breathing',
          'Get 7-9 hours of quality sleep nightly',
        ],
      },
      {
        title: 'Foods That Protect Your Heart',
        icon: '🥗',
        tips: [
          'Fatty fish (salmon, mackerel, tilapia) — omega-3 fatty acids',
          'Avocados — healthy monounsaturated fats and potassium',
          'Dark leafy greens (spinach, sukuma wiki) — rich in nitrates',
          'Whole grains (brown rice, oats, millet) — fiber reduces cholesterol',
          'Garlic — lowers blood pressure and cholesterol',
          'Beans and legumes — reduce LDL cholesterol',
          'Tomatoes — lycopene reduces inflammation',
          'Reduce: red meat, fried foods, sugar, processed snacks',
        ],
      },
      {
        title: 'Warning Signs — See a Doctor Immediately',
        icon: '🚨',
        tips: [
          'Chest pain, pressure, tightness, or squeezing',
          'Pain spreading to arm, jaw, neck, or back',
          'Sudden shortness of breath at rest or with minimal activity',
          'Rapid or irregular heartbeat (palpitations)',
          'Dizziness, lightheadedness, or fainting',
          'Sudden severe fatigue, especially in women',
          'Cold sweats with chest discomfort',
          'Severe ankle swelling that appears suddenly',
        ],
      },
      {
        title: 'Know Your Numbers',
        icon: '📊',
        tips: [
          'Blood pressure: Aim for below 120/80 mmHg',
          'Total cholesterol: Below 200 mg/dL is desirable',
          'Fasting blood sugar: Below 100 mg/dL (normal)',
          'BMI: Aim for 18.5 to 24.9 (healthy range)',
          'Resting heart rate: 60-100 beats per minute',
          'Check these at least once a year if over 40',
        ],
      },
    ],
  },

  kidney: {
    title: 'Kidney Health',
    emoji: '🫘',
    color: '#0E7490',
    colorBg: '#ECFEFF',
    overview: 'Your two kidneys filter about 200 liters of blood daily and produce urine to remove waste. Early kidney disease has no symptoms — making awareness of visible signs critically important.',
    sections: [
      {
        title: 'How to Protect Your Kidneys',
        icon: '🛡️',
        tips: [
          'Drink 8-10 glasses of clean water daily — dehydration strains kidneys',
          'Control blood pressure — high BP is the #1 cause of kidney failure',
          'Manage blood sugar — diabetes is the #2 cause of kidney failure',
          'Avoid overuse of painkillers (ibuprofen, diclofenac) — they damage kidneys',
          'Reduce salt — high sodium raises blood pressure and overworks kidneys',
          'Maintain a healthy weight — obesity increases kidney disease risk',
          'Stop smoking — smoking reduces blood flow to the kidneys',
          'Exercise regularly to improve overall circulation',
        ],
      },
      {
        title: 'Kidney-Friendly Foods',
        icon: '🥦',
        tips: [
          'Cabbage — low in potassium, high in vitamins K and C',
          'Cauliflower — low potassium, high in fiber',
          'Blueberries — anti-inflammatory antioxidants',
          'Egg whites — high protein with less phosphorus than egg yolks',
          'Garlic — anti-inflammatory, reduces sodium needs',
          'Onions — low potassium, flavorful salt alternative',
          'Red grapes — resveratrol protects kidneys from inflammation',
          'Avoid: bananas, oranges, potatoes if kidneys are already impaired (high potassium)',
        ],
      },
      {
        title: 'Warning Signs — See a Doctor Immediately',
        icon: '🚨',
        tips: [
          'Urine that is foamy, bubbly, or frothy (protein leaking)',
          'Blood in urine (red, pink, or cola-colored)',
          'Urinating much less than normal or not at all',
          'Severe puffiness around the eyes, especially in the morning',
          'Severe swelling of legs, ankles, and feet',
          'Persistent fatigue and weakness (anemia from kidney failure)',
          'Nausea, vomiting, or loss of appetite with no other cause',
          'Itchy skin all over the body (uremia)',
        ],
      },
      {
        title: 'High Risk Groups',
        icon: '⚠️',
        tips: [
          'Diabetics — check kidney function (eGFR) annually',
          'People with hypertension — monitor kidney function regularly',
          'Family history of kidney disease — screen early',
          'People over 60 years old — kidney function naturally declines',
          'Those who frequently use NSAIDs (painkillers)',
          'People with recurrent urinary tract infections',
          'HIV positive individuals on certain medications',
        ],
      },
    ],
  },

  liver: {
    title: 'Liver Health',
    emoji: '🟤',
    color: '#B45309',
    colorBg: '#FFFBEB',
    overview: 'The liver is the body\'s largest internal organ, performing over 500 vital functions including detoxification, protein synthesis, and bile production. It is remarkably resilient — but once severely damaged, recovery is difficult.',
    sections: [
      {
        title: 'How to Cleanse & Strengthen Your Liver',
        icon: '🌿',
        tips: [
          'Reduce or eliminate alcohol — even moderate drinking stresses the liver',
          'Drink coffee (unsweetened) — studies show it reduces liver disease risk',
          'Stay hydrated — water helps the liver flush toxins efficiently',
          'Exercise regularly — reduces fat accumulation in the liver',
          'Maintain a healthy weight — fatty liver is now epidemic in Africa',
          'Avoid unnecessary medications and herbal concoctions without doctor approval',
          'Get vaccinated against Hepatitis A and B',
          'Practice safe sex and avoid sharing needles (Hepatitis B/C prevention)',
        ],
      },
      {
        title: 'Liver-Healing Foods',
        icon: '🥬',
        tips: [
          'Coffee — lowers risk of cirrhosis and liver cancer',
          'Green tea — antioxidants improve liver enzyme levels',
          'Grapefruit — contains antioxidants that protect liver cells',
          'Beetroot — reduces liver inflammation and oxidative damage',
          'Cruciferous vegetables (broccoli, cabbage) — stimulate liver detox enzymes',
          'Olive oil — reduces fat accumulation in the liver',
          'Nuts (especially walnuts) — rich in omega-3 fatty acids',
          'Avoid: alcohol, excess sugar, refined carbs, processed and fried foods',
        ],
      },
      {
        title: 'Warning Signs — See a Doctor Immediately',
        icon: '🚨',
        tips: [
          'Yellow skin or white of eyes (jaundice) — urgent medical attention',
          'Severe abdominal pain, especially upper right side',
          'Abdomen becoming visibly large and distended (ascites)',
          'Confusion, disorientation, or personality changes (hepatic encephalopathy)',
          'Vomiting blood or passing very dark/black stool',
          'Extreme fatigue that does not improve with rest',
          'Persistent itching all over the body',
          'Dark urine (tea or cola colored) with pale stool',
        ],
      },
      {
        title: 'Common Liver Diseases in Uganda/East Africa',
        icon: '🌍',
        tips: [
          'Hepatitis B — very common; get vaccinated and tested',
          'Hepatitis C — spread through blood; test if you had surgery or transfusions',
          'Non-Alcoholic Fatty Liver Disease (NAFLD) — rising due to dietary changes',
          'Liver cancer (Hepatocellular Carcinoma) — often linked to Hepatitis B',
          'Alcoholic liver disease — caused by chronic heavy alcohol use',
          'Malaria complications — can affect liver enzyme levels',
          'Aflatoxin exposure from poorly stored grains — increases liver cancer risk',
        ],
      },
    ],
  },
};
