export const ORGANS = {
  heart: {
    id: 'heart',
    name: 'Heart',
    emoji: '❤️',
    tagline: 'Cardiovascular Health',
    description: 'Detect early warning signs of heart disease through visible physical indicators.',
    color: '#DC2626',
    colorLight: '#EF4444',
    colorBg: '#FEF2F2',
    colorBorder: '#FECACA',
    grad: ['#EF4444', '#991B1B'],
  },
  kidney: {
    id: 'kidney',
    name: 'Kidney',
    emoji: '🫘',
    tagline: 'Renal Health',
    description: 'Identify visible signs of kidney dysfunction before they become critical.',
    color: '#0E7490',
    colorLight: '#0891B2',
    colorBg: '#ECFEFF',
    colorBorder: '#A5F3FC',
    grad: ['#06B6D4', '#0E7490'],
  },
  liver: {
    id: 'liver',
    name: 'Liver',
    emoji: '🟤',
    tagline: 'Hepatic Health',
    description: 'Spot early hepatic warning signs for timely intervention.',
    color: '#B45309',
    colorLight: '#D97706',
    colorBg: '#FFFBEB',
    colorBorder: '#FDE68A',
    grad: ['#F59E0B', '#92400E'],
  },
};

export const SYMPTOMS = {
  heart: [
    {
      id: 'h1',
      name: "Diagonal Earlobe Crease (Frank's Sign)",
      shortName: "Earlobe Crease",
      description: 'A diagonal crease running from the tragus to the outer edge of the earlobe at a 45° angle.',
      why: 'Associated with poor circulation and atherosclerosis affecting small blood vessels.',
      severity: 'high',
      canPhoto: true,
      photoGuide: 'Take a clear close-up photo of your earlobe, ensuring good lighting.',
      icon: '👂',
    },
    {
      id: 'h2',
      name: 'Arcus Senilis (Eye Ring)',
      shortName: 'White Eye Ring',
      description: 'A white, gray, or blue arc or ring around the outer edge of the cornea.',
      why: 'In people under 45, this ring may indicate high cholesterol linked to heart disease.',
      severity: 'medium',
      canPhoto: true,
      photoGuide: 'Look straight ahead and take a close-up photo of your eye.',
      icon: '👁️',
    },
    {
      id: 'h3',
      name: 'Xanthelasma (Eyelid Deposits)',
      shortName: 'Eyelid Yellow Patches',
      description: 'Yellowish, flat or slightly raised deposits on the upper or lower eyelids.',
      why: 'These are cholesterol deposits under the skin, a risk marker for heart disease.',
      severity: 'high',
      canPhoto: true,
      photoGuide: 'Take a close-up photo of your eyelid area in natural light.',
      icon: '🟡',
    },
    {
      id: 'h4',
      name: 'Peripheral Edema (Swollen Ankles)',
      shortName: 'Swollen Ankles/Feet',
      description: 'Abnormal swelling in the lower legs, ankles, or feet that leaves a pit when pressed.',
      why: 'Can indicate heart failure where the heart is not pumping blood efficiently.',
      severity: 'high',
      canPhoto: true,
      photoGuide: 'Take a photo of your ankles/feet, or press the area and photograph the indent.',
      icon: '🦵',
    },
    {
      id: 'h5',
      name: 'Nail Clubbing',
      shortName: 'Clubbed Fingernails',
      description: 'Fingertips enlarge and nails curve downward, resembling an upside-down spoon.',
      why: 'Associated with chronic low oxygen levels, which can indicate heart or lung disease.',
      severity: 'high',
      canPhoto: true,
      photoGuide: 'Take a clear photo of your fingernails from the side profile.',
      icon: '💅',
    },
  ],

  kidney: [
    {
      id: 'k1',
      name: "Periorbital Edema (Puffy Eyes)",
      shortName: 'Puffy Face/Eyes (Morning)',
      description: 'Swelling and puffiness around the eyes, especially noticeable in the morning.',
      why: 'Kidneys failing to filter protein cause fluid and protein to leak, leading to facial swelling.',
      severity: 'high',
      canPhoto: true,
      photoGuide: 'Photograph your face immediately after waking in the morning.',
      icon: '😮',
    },
    {
      id: 'k2',
      name: "Half-and-Half Nails (Lindsay's Nails)",
      shortName: 'Half-White Half-Brown Nails',
      description: 'The lower half of the nail appears white and the upper half appears brown or pink.',
      why: 'A classic sign of chronic kidney disease affecting nail pigmentation.',
      severity: 'high',
      canPhoto: true,
      photoGuide: 'Take a clear, well-lit photo of your fingernails from above.',
      icon: '🔳',
    },
    {
      id: 'k3',
      name: 'Pale Conjunctiva',
      shortName: 'Pale Inner Eye Lining',
      description: 'The inner lining of the lower eyelid is pale pink or white instead of healthy red.',
      why: 'Kidney disease causes anemia, reducing red blood cells, making tissues appear pale.',
      severity: 'medium',
      canPhoto: true,
      photoGuide: 'Gently pull down your lower eyelid and photograph the inner lining.',
      icon: '👁️',
    },
    {
      id: 'k4',
      name: 'Severe Ankle Edema',
      shortName: 'Severely Swollen Ankles',
      description: 'Significant bilateral swelling of the ankles and lower legs that is worse by evening.',
      why: 'Kidneys failing to regulate fluid cause sodium and water retention leading to edema.',
      severity: 'high',
      canPhoto: true,
      photoGuide: 'Photograph both ankles together to show the swelling comparison.',
      icon: '🦶',
    },
    {
      id: 'k5',
      name: 'Uremic Frost',
      shortName: 'White Crystal Deposits on Skin',
      description: 'White or yellowish crystal deposits visible on the skin surface, especially forehead.',
      why: 'In severe kidney failure, urea crystallizes on the skin as the body tries to excrete waste.',
      severity: 'critical',
      canPhoto: true,
      photoGuide: 'Take a close-up photo of the affected skin area in bright lighting.',
      icon: '❄️',
    },
  ],

  liver: [
    {
      id: 'l1',
      name: 'Jaundice (Yellow Eyes/Skin)',
      shortName: 'Yellow Eyes or Skin',
      description: 'Yellowing of the skin and the whites of the eyes (scleral icterus).',
      why: 'A damaged liver cannot process bilirubin, causing it to build up and turn tissue yellow.',
      severity: 'critical',
      canPhoto: true,
      photoGuide: 'Photograph your eye whites in natural daylight, or affected skin areas.',
      icon: '🟡',
    },
    {
      id: 'l2',
      name: 'Palmar Erythema (Red Palms)',
      shortName: 'Red Palms',
      description: 'Redness of the palms, particularly the outer edges (thenar and hypothenar areas).',
      why: 'Liver disease causes hormonal changes that dilate blood vessels in the palms.',
      severity: 'medium',
      canPhoto: true,
      photoGuide: 'Photograph the palm of your hand in natural, bright lighting.',
      icon: '✋',
    },
    {
      id: 'l3',
      name: 'Spider Angiomas',
      shortName: 'Spider-Shaped Skin Spots',
      description: 'Small spider-like blood vessel formations visible on the face, chest, or hands.',
      why: 'Excess estrogen from liver dysfunction causes small blood vessel abnormalities.',
      severity: 'medium',
      canPhoto: true,
      photoGuide: 'Take a close-up photo of the spider-like marks on your skin.',
      icon: '🕷️',
    },
    {
      id: 'l4',
      name: "Terry's Nails (White Nails)",
      shortName: 'White Fingernails',
      description: 'Nails appear mostly white with only a narrow pink or brown band at the tip.',
      why: 'Associated with cirrhosis and other severe liver conditions affecting nail vascularity.',
      severity: 'high',
      canPhoto: true,
      photoGuide: 'Take a well-lit photo of your fingernails from above.',
      icon: '🤍',
    },
    {
      id: 'l5',
      name: 'Hepatic Fetor (Distinctive Breath)',
      shortName: 'Sweet/Musty Breath Odor',
      description: 'A distinctive musty, sweet, or fecal smell on the breath (cannot be photographed).',
      why: 'Liver failure causes toxic compounds like dimethyl sulfide to be excreted through the lungs.',
      severity: 'critical',
      canPhoto: false,
      photoGuide: null,
      icon: '💨',
    },
  ],
};
